-- =============================================================================
-- Label Template Industrial Seed Script
-- Project: Print Marking Station — Station Agent
-- Target DB: printer.db (SQLite / printer-adapter)
-- SAFE TO RUN MULTIPLE TIMES: INSERT OR IGNORE skips existing rows.
-- =============================================================================

-- 1. Add new metadata columns (SQLite: will error if column exists — wrap in try/catch or run via EF migration)
ALTER TABLE label_templates ADD COLUMN template_code TEXT;
ALTER TABLE label_templates ADD COLUMN category TEXT;
ALTER TABLE label_templates ADD COLUMN orientation TEXT NOT NULL DEFAULT 'PORTRAIT';
ALTER TABLE label_templates ADD COLUMN revision TEXT NOT NULL DEFAULT 'A';
ALTER TABLE label_templates ADD COLUMN supported_barcode_types TEXT;
ALTER TABLE label_templates ADD COLUMN supported_printer_models TEXT;
ALTER TABLE label_templates ADD COLUMN compatible_station_types TEXT;

-- 2. Unique index on template_code (nullable-safe)
CREATE UNIQUE INDEX IF NOT EXISTS ix_label_templates_template_code
    ON label_templates (template_code) WHERE template_code IS NOT NULL;

-- 3. Insert 9 industrial templates (INSERT OR IGNORE = idempotent)
INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Industrial Product QR Label','Won Seal Tech Co., Ltd. 50x30mm standard product label with QR code.','LBL-PRODUCT-50x30','PRODUCT',203,50.0,30.0,'LANDSCAPE','A','["QR"]','["GK420t","ZT230","ZT410"]','["PRINT_STATION","MARK_STATION"]','{"width":50,"height":30,"dpi":203,"elements":[{"type":"text","x":10,"y":15,"fontSize":11,"text":"WON SEAL TECH CO., LTD."},{"type":"text","x":10,"y":50,"fontSize":10,"binding":"product_name","defaultValue":"Bearing Seal"},{"type":"text","x":10,"y":85,"fontSize":8,"text":"Product:"},{"type":"text","x":90,"y":85,"fontSize":9,"binding":"product_code","defaultValue":"BEARING-SEAL-01"},{"type":"text","x":10,"y":115,"fontSize":8,"text":"Serial:"},{"type":"text","x":90,"y":115,"fontSize":9,"binding":"serial_number","defaultValue":"SN-000001"},{"type":"text","x":10,"y":145,"fontSize":7,"binding":"batch_number","defaultValue":"BATCH-01"},{"type":"text","x":150,"y":145,"fontSize":7,"text":"Rev:"},{"type":"text","x":185,"y":145,"fontSize":7,"binding":"revision","defaultValue":"A"},{"type":"text","x":10,"y":170,"fontSize":7,"binding":"production_date","defaultValue":"2026-07-09"},{"type":"qr","x":280,"y":50,"magnification":4,"payloadTemplate":"{\"sn\":\"{serial_number}\",\"prod\":\"{product_code}\",\"rev\":\"{revision}\",\"batch\":\"{batch_number}\"}"}]}',1,1,'published',1,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Shelf / Rack Location Label','Warehouse location identification. 50x30mm with QR and Code128.','LBL-SHELF-50x30','SHELF',203,50.0,30.0,'LANDSCAPE','A','["CODE128","QR"]','["GK420t","ZD420","ZT230"]','["WAREHOUSE","PRINT_STATION"]','{"width":50,"height":30,"dpi":203,"elements":[{"type":"text","x":10,"y":12,"fontSize":9,"text":"LOCATION"},{"type":"text","x":10,"y":45,"fontSize":18,"binding":"location_code","defaultValue":"A-01-03"},{"type":"text","x":10,"y":100,"fontSize":7,"binding":"zone","defaultValue":"Zone A - Row 1"},{"type":"barcode","x":10,"y":125,"height":50,"symbology":"CODE128","barWidth":2,"binding":"location_code","defaultValue":"A-01-03"},{"type":"qr","x":300,"y":30,"magnification":3,"binding":"location_code","defaultValue":"A-01-03"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Inspection / Supervisor Label','QC inspection records, supervisor sign-off. 100x60mm, Code128.','LBL-INSP-100x60','INSPECTION',203,100.0,60.0,'LANDSCAPE','A','["CODE128"]','["GK420t","ZT230","ZT410"]','["QC_STATION","PRINT_STATION"]','{"width":100,"height":60,"dpi":203,"elements":[{"type":"rect","x":5,"y":5,"width":790,"height":470,"strokeWidth":3},{"type":"text","x":15,"y":20,"fontSize":16,"text":"INSPECTION RECORD"},{"type":"line","x":5,"y":65,"width":790,"height":2},{"type":"text","x":15,"y":80,"fontSize":9,"text":"Job No:"},{"type":"text","x":120,"y":80,"fontSize":10,"binding":"production_order","defaultValue":"PO-2026-001"},{"type":"text","x":15,"y":120,"fontSize":9,"text":"Product:"},{"type":"text","x":120,"y":120,"fontSize":10,"binding":"product_code","defaultValue":"BEARING-SEAL-01"},{"type":"text","x":15,"y":160,"fontSize":9,"text":"Serial:"},{"type":"text","x":120,"y":160,"fontSize":10,"binding":"serial_number","defaultValue":"SN-000001"},{"type":"text","x":15,"y":200,"fontSize":9,"text":"Inspector:"},{"type":"text","x":120,"y":200,"fontSize":10,"binding":"operator","defaultValue":"Inspector A"},{"type":"text","x":15,"y":240,"fontSize":9,"text":"Date:"},{"type":"text","x":120,"y":240,"fontSize":9,"binding":"production_date","defaultValue":"2026-07-09"},{"type":"text","x":15,"y":280,"fontSize":9,"text":"Result:"},{"type":"text","x":120,"y":280,"fontSize":14,"binding":"inspection_result","defaultValue":"PASS"},{"type":"barcode","x":15,"y":320,"height":80,"symbology":"CODE128","barWidth":2,"binding":"serial_number","defaultValue":"SN-000001"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Roll / Material Reel Label','Rubber rolls and raw material reels. 100x80mm with large Code128.','LBL-ROLL-100x80','MATERIAL',203,100.0,80.0,'PORTRAIT','A','["CODE128"]','["ZT230","ZT410","ZT610"]','["WAREHOUSE","MATERIAL_STATION"]','{"width":100,"height":80,"dpi":203,"elements":[{"type":"text","x":15,"y":15,"fontSize":13,"text":"MATERIAL REEL"},{"type":"line","x":5,"y":55,"width":790,"height":2},{"type":"text","x":15,"y":70,"fontSize":9,"text":"Material:"},{"type":"text","x":130,"y":70,"fontSize":11,"binding":"material","defaultValue":"NBR-70 Rubber"},{"type":"text","x":15,"y":110,"fontSize":9,"text":"Lot No:"},{"type":"text","x":130,"y":110,"fontSize":11,"binding":"lot_number","defaultValue":"LOT-2026-07-A"},{"type":"text","x":15,"y":150,"fontSize":9,"text":"Roll ID:"},{"type":"text","x":130,"y":150,"fontSize":11,"binding":"serial_number","defaultValue":"ROLL-001"},{"type":"text","x":15,"y":190,"fontSize":9,"text":"Weight (kg):"},{"type":"text","x":200,"y":190,"fontSize":11,"binding":"weight","defaultValue":"25.0"},{"type":"text","x":15,"y":230,"fontSize":9,"text":"MFG Date:"},{"type":"text","x":130,"y":230,"fontSize":9,"binding":"manufacture_date","defaultValue":"2026-07-09"},{"type":"barcode","x":15,"y":280,"height":130,"symbology":"CODE128","barWidth":3,"binding":"serial_number","defaultValue":"ROLL-001"},{"type":"text","x":15,"y":420,"fontSize":7,"binding":"lot_number","defaultValue":"LOT-2026-07-A"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Pallet Label','Shipping, warehouse and forklift scanning pallet label. 100x150mm.','LBL-PALLET-100x150','PALLET',203,100.0,150.0,'PORTRAIT','A','["CODE128","QR"]','["ZT410","ZT610","ZT620"]','["WAREHOUSE","SHIPPING_STATION"]','{"width":100,"height":150,"dpi":203,"elements":[{"type":"rect","x":5,"y":5,"width":790,"height":1190,"strokeWidth":4},{"type":"text","x":20,"y":20,"fontSize":18,"text":"PALLET"},{"type":"line","x":5,"y":75,"width":790,"height":3},{"type":"qr","x":30,"y":90,"magnification":8,"payloadTemplate":"{\"pallet\":\"{serial_number}\",\"po\":\"{production_order}\",\"prod\":\"{product_code}\"}"},{"type":"text","x":430,"y":90,"fontSize":8,"text":"Order:"},{"type":"text","x":430,"y":120,"fontSize":11,"binding":"production_order","defaultValue":"PO-2026-001"},{"type":"text","x":430,"y":160,"fontSize":8,"text":"Product:"},{"type":"text","x":430,"y":190,"fontSize":10,"binding":"product_code","defaultValue":"BEARING-SEAL-01"},{"type":"text","x":430,"y":230,"fontSize":8,"text":"Pallet ID:"},{"type":"text","x":430,"y":260,"fontSize":10,"binding":"serial_number","defaultValue":"PLT-001"},{"type":"text","x":430,"y":300,"fontSize":8,"text":"Qty:"},{"type":"text","x":430,"y":330,"fontSize":14,"binding":"quantity","defaultValue":"100"},{"type":"barcode","x":20,"y":600,"height":150,"symbology":"CODE128","barWidth":4,"binding":"serial_number","defaultValue":"PLT-001"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Parent Rubber Sheet Label','Parent sheet identification for rubber sheet tracking. 80x50mm with QR.','LBL-SHEET-P-80x50','SHEET',203,80.0,50.0,'LANDSCAPE','A','["QR"]','["GK420t","ZT230"]','["MATERIAL_STATION","PRINT_STATION"]','{"width":80,"height":50,"dpi":203,"elements":[{"type":"text","x":10,"y":12,"fontSize":11,"text":"PARENT SHEET"},{"type":"line","x":5,"y":45,"width":530,"height":2},{"type":"text","x":10,"y":60,"fontSize":9,"text":"Sheet ID:"},{"type":"text","x":120,"y":60,"fontSize":11,"binding":"serial_number","defaultValue":"SHEET-P-001"},{"type":"text","x":10,"y":100,"fontSize":9,"text":"Material:"},{"type":"text","x":120,"y":100,"fontSize":10,"binding":"material","defaultValue":"NBR-70"},{"type":"text","x":10,"y":140,"fontSize":9,"text":"Lot:"},{"type":"text","x":80,"y":140,"fontSize":9,"binding":"lot_number","defaultValue":"LOT-2026-07-A"},{"type":"text","x":10,"y":220,"fontSize":8,"binding":"manufacture_date","defaultValue":"2026-07-09"},{"type":"qr","x":570,"y":40,"magnification":6,"payloadTemplate":"{\"sheet\":\"{serial_number}\",\"lot\":\"{lot_number}\",\"mat\":\"{material}\"}"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Child Rubber Sheet Label','Individual child sheet tracking cut from parent. 50x30mm compact QR.','LBL-SHEET-C-50x30','SHEET',203,50.0,30.0,'LANDSCAPE','A','["QR"]','["GK420t","ZD420"]','["MATERIAL_STATION","PRINT_STATION"]','{"width":50,"height":30,"dpi":203,"elements":[{"type":"text","x":8,"y":10,"fontSize":9,"text":"CHILD SHEET"},{"type":"text","x":8,"y":40,"fontSize":8,"binding":"serial_number","defaultValue":"SHEET-C-001"},{"type":"text","x":8,"y":70,"fontSize":7,"binding":"lot_number","defaultValue":"LOT-2026-07-A"},{"type":"text","x":8,"y":100,"fontSize":7,"text":"Parent:"},{"type":"text","x":90,"y":100,"fontSize":7,"binding":"parent_id","defaultValue":"SHEET-P-001"},{"type":"text","x":8,"y":130,"fontSize":7,"binding":"manufacture_date","defaultValue":"2026-07-09"},{"type":"qr","x":270,"y":30,"magnification":3,"binding":"serial_number","defaultValue":"SHEET-C-001"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Semi-Finished Product (WIP) Label','MES and operation tracking for work-in-progress items. 60x40mm with QR.','LBL-WIP-60x40','WIP',203,60.0,40.0,'LANDSCAPE','A','["QR"]','["GK420t","ZD420","ZT230"]','["PRINT_STATION","MARK_STATION","WIP_STATION"]','{"width":60,"height":40,"dpi":203,"elements":[{"type":"text","x":8,"y":10,"fontSize":11,"text":"WIP"},{"type":"line","x":5,"y":40,"width":470,"height":2},{"type":"text","x":8,"y":55,"fontSize":9,"text":"Serial:"},{"type":"text","x":95,"y":55,"fontSize":10,"binding":"serial_number","defaultValue":"SN-000001"},{"type":"text","x":8,"y":90,"fontSize":9,"text":"Product:"},{"type":"text","x":95,"y":90,"fontSize":9,"binding":"product_code","defaultValue":"BEARING-SEAL-01"},{"type":"text","x":8,"y":125,"fontSize":9,"text":"Op:"},{"type":"text","x":65,"y":125,"fontSize":9,"binding":"operation","defaultValue":"LASER_MARK"},{"type":"text","x":8,"y":160,"fontSize":8,"text":"Station:"},{"type":"text","x":95,"y":160,"fontSize":8,"binding":"station","defaultValue":"STATION-01"},{"type":"text","x":8,"y":190,"fontSize":7,"binding":"production_date","defaultValue":"2026-07-09"},{"type":"qr","x":500,"y":25,"magnification":5,"payloadTemplate":"{\"sn\":\"{serial_number}\",\"op\":\"{operation}\",\"prod\":\"{product_code}\"}"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO label_templates (id,name,description,template_code,category,dpi,label_width,label_height,orientation,revision,supported_barcode_types,supported_printer_models,compatible_station_types,template_json,version,is_active,status,is_default,created_by,updated_by,created_at,updated_at) VALUES (lower(hex(randomblob(16))),'Material Issue Label','Warehouse to MES material issuance tracking. 100x60mm with QR and Code128.','LBL-ISSUE-100x60','ISSUE',203,100.0,60.0,'LANDSCAPE','A','["CODE128","QR"]','["GK420t","ZT230","ZT410"]','["WAREHOUSE","MATERIAL_STATION"]','{"width":100,"height":60,"dpi":203,"elements":[{"type":"text","x":15,"y":15,"fontSize":13,"text":"MATERIAL ISSUE"},{"type":"line","x":5,"y":55,"width":790,"height":2},{"type":"text","x":15,"y":70,"fontSize":9,"text":"Material:"},{"type":"text","x":130,"y":70,"fontSize":11,"binding":"material","defaultValue":"NBR-70 Rubber"},{"type":"text","x":15,"y":110,"fontSize":9,"text":"Issue No:"},{"type":"text","x":130,"y":110,"fontSize":10,"binding":"serial_number","defaultValue":"ISSUE-001"},{"type":"text","x":15,"y":150,"fontSize":9,"text":"From:"},{"type":"text","x":100,"y":150,"fontSize":9,"binding":"source_location","defaultValue":"WAREHOUSE-A"},{"type":"text","x":15,"y":185,"fontSize":9,"text":"To:"},{"type":"text","x":60,"y":185,"fontSize":9,"binding":"destination","defaultValue":"PRODUCTION-01"},{"type":"text","x":15,"y":220,"fontSize":9,"text":"Qty:"},{"type":"text","x":75,"y":220,"fontSize":11,"binding":"quantity","defaultValue":"50"},{"type":"barcode","x":15,"y":260,"height":80,"symbology":"CODE128","barWidth":2,"binding":"serial_number","defaultValue":"ISSUE-001"},{"type":"qr","x":620,"y":60,"magnification":5,"payloadTemplate":"{\"issue\":\"{serial_number}\",\"mat\":\"{material}\",\"qty\":\"{quantity}\"}"}]}',1,1,'published',0,'system','system',datetime('now'),datetime('now'));

-- Verification:
-- SELECT id, name, template_code, category, label_width, label_height, is_default FROM label_templates ORDER BY category, name;
-- Expected: 9 rows with unique template_codes
